dataloader:
  batch_size: 256
  params:
    padding: 1
    past_k: 9
    path: ./data/etth1.csv
    test: 0.2
    train: 0.7
    window: 96
  shuffle: true
  target: training.dataset.TimeSeriesDataset
model:
  denoiser:
    params:
      kaiser_beta: 14.77
      kaiser_size: 64
      seq_len: 96
      sigma_from_t: false
    target: models.networks.LinearNet
  noise_schedule:
    params:
      ema_beta: 0.99
      scale_from_data: true
      scale_max: 15.333855994148035
      scale_min: 1.018784956670171
      sigma_data: 1.0
      sliding_window: 60
      stats: cumulative
      var_max: 3.531707027201382
      var_min: 0.007987502055765561
    target: models.noise.TEDM
  preconditioning:
    target: models.precond.TEDM
sampler:
  params:
    backward: true
    batch_size: 128
    clamp: true
    deterministic: true
    horizon: 96
    n_tracks: 300
  target: training.sampler.TEDM
trainer:
  ema:
    decay: 0.9982532204186195
    update_interval: 10
  gradient_accumulate_every: 1
  logger:
    params:
      args: None
      enable: true
      env_name: TEDM
      log_freq: 10
      port: 8097
      print_to_console: false
      server: localhost
      verbose: false
    target: training.logger.BaseLogger
  max_epochs: 1210
  optimizer:
    params:
      betas:
      - 0.8129264568578601
      - 0.9134888229627925
      lr: 0.0001357035861919848
      weight_decay: 1.1141180571248792e-05
    target: torch.optim.Adam
  scheduler:
    params:
      factor: 0.2323564540186706
      min_lr: 1.0e-06
      patience: 47
      threshold: 0.01
      threshold_mode: rel
      verbose: false
      warmup: 72
      warmup_lr: 0.0033000503225405343
    target: training.scheduler.ReduceLROnPlateauWithWarmup
  validation_check: false
  validation_viz: false
