dataloader:
  batch_size: 256
  params:
    padding: 1
    past_k: 8
    path: ./data/weather.csv
    test: 0.2
    train: 0.7
    window: 96
  shuffle: true
  target: training.dataset.TimeSeriesDataset
model:
  denoiser:
    params:
      alias_free: true
      dropout: 0.1
      kaiser_beta: 14.77
      kaiser_size: 64
      model_channels: 32
      num_blocks: 2
      num_heads: 1
      rope_attn: true
      seq_len: 96
      sigma_from_t: false
    target: models.networks.UNet
  noise_schedule:
    params:
      ema_beta: 0.99
      scale_from_data: true
      scale_max: 2.170607176135755
      scale_min: 0.108217764349766
      sigma_data: 1.0
      sliding_window: 60
      stats: cumulative
      var_max: 7.6945591297183
      var_min: 4.61732128030248e-05
    target: models.noise.TEDM
  preconditioning:
    target: models.precond.TEDM
sampler:
  params:
    backward: true
    batch_size: 128
    clamp: true
    deterministic: true
    horizon: 96
    n_tracks: 300
  target: training.sampler.TEDM
trainer:
  ema:
    decay: 0.9987464054287827
    update_interval: 10
  gradient_accumulate_every: 3
  logger:
    params:
      args: None
      enable: true
      env_name: TEDM
      log_freq: 10
      port: 8097
      print_to_console: false
      server: localhost
      verbose: false
    target: training.logger.BaseLogger
  max_epochs: 4000
  optimizer:
    params:
      betas:
      - 0.8000840660079692
      - 0.9160572867929465
      lr: 2.5450983118699e-05
      weight_decay: 6.6341912753608e-07
    target: torch.optim.Adam
  scheduler:
    params:
      factor: 0.8393809159287104
      min_lr: 1.0e-06
      patience: 43
      threshold: 0.01
      threshold_mode: rel
      verbose: false
      warmup: 99
      warmup_lr: 0.004390672699787405
    target: training.scheduler.ReduceLROnPlateauWithWarmup
  validation_check: false
  validation_viz: false
